---
kind: pipeline
type: docker
name: build

steps:
  - name: lint
    image: golangci/golangci-lint:v1.43.0
    environment:
      CGO_ENABLED: 0
    commands:
      - golangci-lint run

  - name: test
    image: golang:1.17.3-alpine
    environment:
      CGO_ENABLED: 0
    commands:
      - go test -test.v ./...

  - name: test-race
    image: golang:1.17.3-stretch
    commands:
      - go test -race -test.v ./...

  - name: benchmark
    image: golang:1.17.3-alpine
    environment:
      CGO_ENABLED: 0
    commands:
      - go test -benchmem -run=^$ go.dev.pztrn.name/valiwork -bench .

  - name: benchmark-race
    image: golang:1.17.3-stretch
    commands:
      - go test -benchmem -run=^$ go.dev.pztrn.name/valiwork -race -bench .
