---
kind: pipeline
type: docker
name: build

steps:
  - name: lint
    image: code.pztrn.name/containers/mirror/golangci/golangci-lint:v1.46.2
    environment:
      CGO_ENABLED: 0
    commands:
      - golangci-lint run

  - name: test
    image: code.pztrn.name/containers/mirror/golang:1.18.3-alpine
    environment:
      CGO_ENABLED: 0
    commands:
      - go test -test.v ./...

  - name: test-race
    image: code.pztrn.name/containers/mirror/golang:1.18.3-bullseye
    commands:
      - go test -race -test.v ./...

  - name: benchmark
    image: code.pztrn.name/containers/mirror/golang:1.18.3-alpine
    environment:
      CGO_ENABLED: 0
    commands:
      - go test -benchmem -run=^$ go.dev.pztrn.name/valiwork -bench .

  - name: benchmark-race
    image: code.pztrn.name/containers/mirror/golang:1.18.3-bullseye
    commands:
      - go test -benchmem -run=^$ go.dev.pztrn.name/valiwork -race -bench .
