run:
  deadline: 5m
linters:
  enable-all: true
  disable:
    # Because globals might exist, but according to our codestyle they
    # should be lowercased and considered as unexported.
    - gochecknoglobals
    # While it might be useful it'll create more problems that will solve.
    - gocritic
    # This linter goes crazy for nothing (almost).
    - funlen
    # While "_test" package naming idiom is good - it isn't good for this
    # library (at least for now).
    - testpackage
linters-settings:
  lll:
    line-length: 420
  gocyclo:
    min-complexity: 40
issues:
  exclude-rules:
    # We do not need static errors in tests for now.
    - path: validations_test.go
      linters: 
        - goerr113
    # ...and in example.
    - path: example/main.go
      linters:
        - goerr113
